In [ ]:
import pandas as pd
data = pd.read_csv('/content/cosmetic.csv',encoding='latin-1')
data

,product_name,website,country,category,subcategory,title-href,price,brand,ingredients,form,type,color,size,rating,noofratings
0,"Carlton London Incense Eau da parfum, Premium ...",Flipkart,India,body,perfume,https://www.amazon.in/Carlton-London-Limited-I...,599.0,Carlton London,NaN,aerosol,NaN,"Top Note: Orange Blossom, Blackberry | Heart N...",100,3.9,19
1,CHARLENE SPRAY MIST PERFUME 30 - INTIMATE (PAC...,Flipkart,India,body,perfume,https://www.amazon.in/CHARLENE-SPRAY-MIST-PERF...,149.0,Charlene,NaN,aerosol,NaN,Unit count type:,30,4.4,"4,031"
2,CHARLENE SPRAY MIST PERFUME 30 - INTIMATE (PAC...,Flipkart,India,body,perfume,https://www.amazon.in/CHARLENE-SPRAY-MIST-PERF...,298.0,Charlene,NaN,aerosol,NaN,Unit count type:,30,4.4,"4,072"
3,DENVER Black Code Perfume - 60 | Eau de Parfum...,Flipkart,India,body,perfume,https://www.amazon.in/DENVER-Black-Code-Perfum...,245.0,Denver,NaN,aerosol,NaN,Long-Lasting Scent,60,4.2,61
4,Denver Hamilton Perfume - 100 | Long Lasting P...,Flipkart,India,body,perfume,https://www.amazon.in/Denver-Perfume-Hamilton-...,422.0,Denver,NaN,aerosol,NaN,Long-Lasting Scent,100,4.3,342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12610,Bright Future - Smoothing & Brightening Concea...,Sephora,India,face,concealer,https://sephora.nnnow.com/mac-cosmetics-prep--...,1900.0,MAC Cosmetics,"Water\Aqua\Eau, Glycerin, Butylene Glycol, Toc...",cream,"Combination, Dry, Oily, Normal",Pinklite,100,3.15,14
12611,Bright Future - Smoothing & Brightening Concea...,Sephora,India,face,concealer,https://sephora.nnnow.com/mac-cosmetics-prep--...,2150.0,MAC Cosmetics,"Water\Aqua\Eau, Cyclopentasiloxane, Dimethicon...",cream,"Combination, Dry, Oily, Normal",No colour,100,3.13,13
12612,Starlaa Rosy Bronze Blush Mini,Sephora,India,face,blush,https://sephora.nnnow.com/klara-cosmetics-wome...,3040.0,Klara Cosmetics,"Talc, Ethylhexyl Palmitate, Octyldodecanol, Sy...",powder,"Combination, Oily, Normal, Dry",Selfie Queen,110,4.03,96
12613,Terra Golden Brick Red Blush Travel Size Mini,Sephora,India,face,blush,https://sephora.nnnow.com/clinique-women-clini...,2950.0,CLINIQUE,"Water\Aqua\Eau, Dimethicone, Isododecane, Buty...",liquid,"Combination, Dry, Oily, Normal",All,115,3.15,15
12614,Peachin' Golden Peach Blush Travel Size Mini,Sephora,India,face,blush,https://sephora.nnnow.com/lancome-clarifique-d...,5850.0,Lancme,"Aqua / Water, Alcohol Denat., Glycolic Acid, B...",serum,"Combination, Dry, Normal, Oily",No colour,150,3.16,16

In [ ]:
data.isna().sum()

product_name       0
website            0
country            0
category           0
subcategory        0
title-href         0
price            317
brand              0
ingredients     6015
form               0
type            2681
color           1989
size            3166
rating          2067
noofratings      459
dtype: int64

In [ ]:
data.drop(columns=['ingredients'],inplace=True)

In [ ]:
data.to_csv('cosmetic.csv',index=False,encoding='utf-8')